server:
  port: 8080
  servlet:
    context-path: /
  reactive:
    session:
      cookie:
        secure: false
# 连接池配置
spring:
  application:
    name: user-center-back
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/user_center
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      id-type: auto

