# 连接池配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: lwj1103
    url: jdbc:mysql://www.lwj1103.com:3306/user_center

